kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: akka-cluster-1
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: akka-cluster-1
subjects:
  - kind: Group
    name: 'system:serviceaccounts:akka-cluster-1'
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: akka-cluster-demo
  namespace: akka-cluster-1
  labels:
    app: akka-cluster-demo
spec:
  type: LoadBalancer
  selector:
    app: akka-cluster-demo
  ports:
    - name: http-endpoint
      port: 8080
      targetPort: 8080
    - name: remoting
      port: 25520
      targetPort: 25520
    - name: management
      port: 8558
      targetPort: 8558
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akka-cluster-demo
  name: akka-cluster-demo
  namespace: akka-cluster-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akka-cluster-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akka-cluster-demo
        actorSystemName: akka-cluster-demo
      annotations:
        consul.hashicorp.com/connect-inject: "true"
#        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "25520,8558"
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "25520,8558,8080"
        consul.hashicorp.com/service-tags: system:akka-cluster-demo,akka-management-port:8558
    spec:
      containers:
        - name: akka-cluster-demo
          image: akka-cluster-demo:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 8558
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: "0.1"
              memory: 200Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
